### ISSUE TITLE
Someone can find the error

### ISSUE THREAD

**Issue by dev-mdirfan** [dev-mdirfan/error_metakart_wordpress#1]
Wordpress Dashboard is not  working.

**Comment by BhaskarKulshrestha** [comment]
just reinstall all the execution files .
and restart the mysql server

**Comment by dev-mdirfan** [comment]
Here I have tried but it not solved.
 -
`php
define(engine.init(), "dashboard")
`

**Comment by BhaskarKulshrestha** [comment]
Step 1: Launch the XAMPP Apache configuration settings
First, go ahead and launch the XAMPP dashboard. The program itself doesn’t have to operate. As long as you can access your dashboard, you should be able to resolve the error.

Additionally, try running XAMPP as an administrator. You can do this by right-clicking on the program and selecting Run as administrator. This isn’t crucial for this walkthrough, but it can prevent occasional unrelated errors.

Once you’ve launched XAMPP, navigate to the row titled Apache under the heading Module. Under Actions, select Config:

The launch menu for XAMPP.
Note that when you see the “XAMPP error Apache shutdown unexpectedly” message, that means that the issue is [specifically related to Apache](https://themeisle.com/blog/linux-vs-windows-hosting/). Therefore, you’ll need to click on that specific Config button to properly fix it. None of the other rows in this window will work.

Clicking on the Config button will open a dropdown menu listing a few file names. Each represents a configuration file for the program. Choose the first option, titled Apache (httpd.conf):

Apache Httpd
You can either open it with your default text editor, or a specialized code editor. As long as you can make changes to the file and save them, how you do so doesn’t really matter. We’ll be using Notepad.

Once you open the httpd.conf file, you’ll see some text similar to the following:

A sample configuration file for Apache.
Once again, this can be a bit intimidating if you’re new to editing configuration files. The good news is that you’ll only need to modify a few simple things.

However, we do recommend that you proceed with caution. Configuration files often carry information that is essential for a program’s normal operation. Therefore, try not to edit anything that you don’t understand. You may also want to save a backup of this file before you proceed to the next step.

Step 2: Change your default port settings in httpd.conf
As we already mentioned, when you see the “XAMPP error Apache shutdown unexpectedly” message, it’s almost always a problem with a blocked port. As such, we’ll be changing the ports that the program normally uses to connect to your network.

Unless you’ve changed it before, the default port for Apache is 80. Port 80 is specifically for HTTP programs. However, it’s not just the default for Apache. Many other programs will use port 80 as well, which can lead to conflicts if you try to run multiple programs on this port at once.

To solve this issue, you need to redirect Apache to port 8080. This is an alternate HTTP-specific port. As such, XAMPP will continue to work as normal, but with less likelihood that its port will become blocked again in the future. As such, this is also a preventative measure against future port conflict errors.

Let’s get back to the configuration file. Press Ctrl + F to open a search dialogue. Enter 80 into the field to find every instance of the number in the file:

Opening a search dialogue for port 80 in httpd.conf to resolve the XAMPP error apache shutdown unexpectedly message.
There will probably be a handful of instances where 80 occurs. However, you only need to change a few of them. Specifically, you’ll need to change three items:

Change Port 80 to Port 8080
Change Listen 80 to Listen 8080
Change servername localhost: 80 to servername localhost: 8080
Once again, we encourage you to only change these three items. Not only will modifying unrelated lines not solve this error, but it could also cause another one. If you accidentally edit the wrong element, you can restore your own backup or find the default Apache file [on Github](https://gist.github.com/TheSunMan/4008088).

Save the httpd.conf file and close it when you’re finished making these changes. Then go back to your XAMPP control panel for the last step.

Step 3: Update your default port settings in http-ssl.conf
Lastly, we’ll be editing one final configuration file. To access it, repeat the instructions from Step 1. Go to the Apache row under Module and select Config. However, this time, click on the second option in the dropdown menu, titled Apache (httpd-ssl.conf):

Apache ssl configuration
Open up the text file in your preferred editor. However, this time you won’t be searching for 80. Instead, hit Ctrl + F and search for the number 443.

Port 443 is the port that is typically used for [secure web transactions](https://themeisle.com/blog/cheap-ssl-certificates-for-wordpress/). However, Apache also needs it. Therefore, you need to change two instances of 443 to the alternative port – 4433:

Change Listen 443 to Listen 4433
Change <VirtualHost_default_:443> to <VirtualHost_default_:4433>
Be sure to save your work in this file as well. Once you’re done, close your text or code editor.

Step 4: Restart Apache
The next thing you want to do is restart Apache. This will reset the processes so that Apache can use the new alternate ports you’ve specified.

How to restart Apache on XAMPP
Restarting Apache is easy to do and somewhat intuitive:

Click the Stop button on the Apache row.
After Apache stops, click the Start button to restart it again.
If for some reason that doesn’t work, then you might need to completely shut down XAMPP and relaunch it. In most cases that shouldn’t be necessary though. The stop-start method should do the trick.

Upon restart, everything should work normally. Your control panel should look something like this:

A properly operating XAMPP dashboard with no Apache error.
From here, you should be able to click on Start next to Apache and continue with your work on your local site. Remember to not use ports 8080 or 4433 for any other programs, or you may have to repeat this process.

Once you have resolved this error, you may want to investigate other programs to see which one is taking up Apache’s default ports. If you decide to adjust another program’s settings to disconnect it, you can repeat these steps to reconnect XAMPP to ports 80 and 443.

[Go to top](https://themeisle.com/blog/xampp-error-apache-shutdown-unexpectedly/#)
Conclusion
Having to [troubleshoot an error](https://themeisle.com/blog/what-are-http-error-codes/) when you’re in the middle of a development project is annoying and eats up valuable time. Apache errors in particular can be aggravating. Fortunately, by altering a few configuration files, you can quickly resolve this frustrating roadblock.

[How to fix #XAMPP error 'Apache shutdown unexpectedly' ](https://twitter.com/share?text=How+to+fix+%23XAMPP+error+%27Apache+shutdown+unexpectedly%27+%E2%9A%92%EF%B8%8F%E2%9A%92%EF%B8%8F%E2%9A%92%EF%B8%8F&via=themeisle&related=themeisle&url=https://themeisle.com/blog/xampp-error-apache-shutdown-unexpectedly/)⚒️⚒️⚒️
[CLICK TO TWEET ](https://twitter.com/share?text=How+to+fix+%23XAMPP+error+%27Apache+shutdown+unexpectedly%27+%E2%9A%92%EF%B8%8F%E2%9A%92%EF%B8%8F%E2%9A%92%EF%B8%8F&via=themeisle&related=themeisle&url=https://themeisle.com/blog/xampp-error-apache-shutdown-unexpectedly/)
In this article, we covered four easy steps to resolve the “XAMPP error Apache shutdown unexpectedly” message:

Launch the Apache configuration settings from the XAMPP dashboard.
Open the httpd.conf file and change the default port from 80 to 8080.
Open the http-ssl.conf file and change the default port from 443 to 4433.
Restart Apache.
